apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: notes-universitaires
data:
  POSTGRES_DB: gestion_notes_db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: notes-universitaires
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: VotreMotDePasseSecurise123!